CREATE TABLE activity(
    id integer primary key generated by default as identity,
    name text NOT NULL,
    description TEXT NOT NULL,
     /*
      *  category TEXT NOT NULL,
     */
     isAccepted default bit(1),
     isRejected default bit(1),
     date_created TIMESTAMPTZ default now() NOT NULL
);