CREATE TABLE activity(
    id integer primary key generated by default as identity,
    name text NOT NULL,
    description TEXT NOT NULL,
     /*
      *  category TEXT NOT NULL,
     */
     isAccepted bit string length 0,
     isRejected bit string length 0,
     date_created TIMESTAMPTZ default now() NOT NULL
);